-- Inserir projetos de exemplo (execute apenas se necessário)
INSERT INTO projects (title, description, image_url, tags, url, github_url, featured, status)
VALUES 
  ('E-commerce Moderno', 'Plataforma de e-commerce completa com pagamentos, carrinho e painel administrativo.', '/placeholder.svg?height=600&width=800', ARRAY['Next.js', 'Tailwind CSS', 'Stripe'], '#', '#', true, 'published'),
  ('Dashboard Analytics', 'Dashboard interativo para visualização de dados e métricas de negócios.', '/placeholder.svg?height=600&width=800', ARRAY['React', 'D3.js', 'Firebase'], '#', '#', true, 'published'),
  ('App de Gestão Financeira', 'Aplicativo para controle de finanças pessoais com gráficos e relatórios.', '/placeholder.svg?height=600&width=800', ARRAY['React Native', 'TypeScript', 'Node.js'], '#', '#', true, 'published')
ON CONFLICT DO NOTHING;

-- Inserir posts de exemplo (execute apenas se necessário)
INSERT INTO posts (title, slug, content, excerpt, image_url, tags, featured, status)
VALUES 
  ('Introdução ao Next.js', 'introducao-ao-nextjs', '# Introdução ao Next.js\n\nNext.js é um framework React que permite funcionalidades como renderização do lado do servidor e geração de sites estáticos para aplicativos da web baseados em React.\n\n## Por que usar Next.js?\n\n- **Renderização do lado do servidor (SSR)**: Melhora o SEO e o desempenho inicial da página\n- **Geração de site estático (SSG)**: Pré-renderiza páginas para carregamento ultra-rápido\n- **Divisão de código automática**: Carrega apenas o JavaScript necessário\n- **Roteamento baseado em sistema de arquivos**: Simplifica a navegação\n- **Suporte a API Routes**: Crie APIs sem configurar um servidor separado', 'Next.js é um framework React que permite funcionalidades como renderização do lado do servidor e geração de sites estáticos para aplicativos da web baseados em React.', '/placeholder.svg?height=600&width=800', ARRAY['Next.js', 'React', 'JavaScript'], true, 'published'),
  ('Estilizando com Tailwind CSS', 'estilizando-com-tailwind-css', '# Estilizando com Tailwind CSS\n\nTailwind CSS é um framework CSS utilitário de baixo nível que permite construir designs personalizados sem sair do seu HTML.\n\n## Vantagens do Tailwind CSS\n\n- **Desenvolvimento mais rápido**: Aplique estilos diretamente no HTML sem alternar entre arquivos\n- **Altamente personalizável**: Configure cores, espaçamentos, fontes e muito mais\n- **Otimizado para produção**: Remove automaticamente estilos não utilizados\n- **Responsivo por padrão**: Utilitários integrados para design responsivo\n- **Componentes consistentes**: Crie sistemas de design coesos', 'Tailwind CSS é um framework CSS utilitário de baixo nível que permite construir designs personalizados sem sair do seu HTML.', '/placeholder.svg?height=600&width=800', ARRAY['CSS', 'Tailwind', 'Design'], false, 'published'),
  ('Integrando Supabase com React', 'integrando-supabase-com-react', '# Integrando Supabase com React\n\nSupabase é uma alternativa de código aberto ao Firebase, oferecendo banco de dados PostgreSQL, autenticação, APIs instantâneas e muito mais.\n\n## Como integrar Supabase com React\n\n1. **Instalação**: `npm install @supabase/supabase-js`\n2. **Configuração**: Crie um cliente Supabase com suas credenciais\n3. **Autenticação**: Implemente login, registro e gerenciamento de sessão\n4. **Banco de dados**: Execute consultas e ouça atualizações em tempo real\n5. **Armazenamento**: Faça upload e gerencie arquivos', 'Supabase é uma alternativa de código aberto ao Firebase, oferecendo banco de dados PostgreSQL, autenticação, APIs instantâneas e muito mais.', '/placeholder.svg?height=600&width=800', ARRAY['Supabase', 'React', 'Backend'], false, 'published')
ON CONFLICT DO NOTHING;

-- Criar um usuário admin (descomente e execute apenas em ambiente de desenvolvimento)
-- SELECT create_admin_user('admin@axolutions.com.br', 'senha_segura', 'Administrador');
